---
title: Home
description: Bioinformatic Data Science Lab of Jia-Ming Chang at National Chengchi University — computational
  approaches to genomics and protein function.
include-in-header:
  text: "<link rel=\"me\" href=\"https://orcid.org/0000-0002-6711-1739\">\n<meta name=\"author\" content=\"\
    Jia-Ming Chang (張家銘)\">\n<script type=\"application/ld+json\">\n{\n  \"@context\": \"https://schema.org\"\
    ,\n  \"@type\": \"ResearchOrganization\",\n  \"name\": \"Bioinformatic Data Science Lab, NCCU\",\n\
    \  \"url\": \"https://changlabtw.github.io/lab/\",\n  \"alternateName\": \"BIOINFORMATICS@CS.NCCU\"\
    ,\n  \"parentOrganization\": {\n    \"@type\": \"Organization\",\n    \"name\": \"National Chengchi\
    \ University\",\n    \"identifier\": \"https://ror.org/03rqk8h36\"\n  },\n  \"member\": {\n    \"\
    @type\": \"Person\",\n    \"name\": \"Jia-Ming Chang\"\n  }\n}\n</script>\n"
---

::: {.hero}
::: {.hero-inner}
[Department of Computer Science · National Chengchi University]{.tagline}

# Bioinformatic Data Science Lab

We aim to address biology questions through computational approach, i.e., design
algorithm for sequence alignment/phylogenetic reconstruction, explore machine
learning in protein function prediction, apply data science on cancer genomics.
:::
:::

## News

::: {.news-list}
::: {.news-item}
[2026]{.news-date}[service]{.news-cat .news-cat-service}

[Program Committee, InCoB/ISCB-APAC 2026](https://incob.apbionet.org/incob2026/committee/)
:::
::: {.news-item}
[2024-11]{.news-date}[service]{.news-cat .news-cat-service}

[出任 NAR Genomics and Bioinformatics Deputy Editor](https://academic.oup.com/nargab/pages/Editorial_Board)
:::
::: {.news-item}
[2023-02]{.news-date}[paper]{.news-cat .news-cat-paper}

[Science Advances 論文發表:Topological screen identifies hundreds of Cp190- and CTCF-dependent Drosophila chromatin insulator elements](https://doi.org/10.1126/sciadv.ade0090)
:::
:::

[All news →](news.html){.news-more}

## Research

::: {.card-grid}
::: {}
**[3D Genome Organization](research.html#3d-genome)**

Hi-C and Micro-C analysis of TADs, chromatin loops and compartments
:::
::: {}
**[Sequence Alignment & Phylogenetics](research.html#alignment-phylogenetics)**

Alignment reliability, bootstrap support and evolutionary modeling
:::
::: {}
**[Single-Cell Data Analysis](research.html#single-cell)**

Hierarchical clustering and visualization of single-cell data
:::
::: {}
**[Protein Function Prediction](research.html#protein-function)**

Subcellular localization and Gene Ontology prediction from sequence
:::
:::
